import assert from 'node:assert/strict';
import {validateChannels,selectStream,manifest} from './update.mjs';
const now=1700000000000;
const info={is_live:true,protocol:'m3u8_native',acodec:'mp4a',vcodec:'avc1',url:'https://manifest.googlevideo.com/api/manifest/hls_playlist/expire/1700021600/playlist.m3u8',tbr:1500,width:1280,height:720};
assert.throws(()=>validateChannels([]));
assert.throws(()=>validateChannels([{id:'../escape',name:'A',url:'https://youtube.com/watch?v=example'}]));
assert.throws(()=>validateChannels([{id:'test',name:'A',url:'https://other.example/'}]));
assert.equal(validateChannels([{id:'test',name:'A',url:'https://www.youtube.com/watch?v=example'}]).length,1);
assert.throws(()=>selectStream({...info,is_live:false},now));
assert.throws(()=>selectStream({...info,acodec:'none'},now));
assert.throws(()=>selectStream({...info,url:'https://manifest.googlevideo.com/expire/1700000010/'},now));
assert.throws(()=>selectStream({...info,url:'https://googlevideo.com.evil.example/expire/1700021600/'},now));
const s=selectStream(info,now);assert.equal(s.bandwidth,1500000);
assert.ok(manifest(s).includes('RESOLUTION=1280x720'));
assert.ok(!manifest({...s,width:null,height:null}).includes('RESOLUTION'));
const video={...info,acodec:'none'};
const audio={...info,vcodec:'none',acodec:undefined,tbr:null};
const split=selectStream({is_live:true,requested_formats:[video,audio]},now);
assert.equal(split.audioUrl,audio.url);
assert.equal(split.bandwidth,1692000);
assert.ok(manifest(split).includes('TYPE=AUDIO,GROUP-ID="audio"'));
assert.ok(manifest(split).includes('AUDIO="audio"'));
assert.throws(()=>selectStream({is_live:true,requested_formats:[video]},now));
assert.throws(()=>selectStream({is_live:true,requested_formats:[video,{...audio,url:'https://manifest.googlevideo.com/expire/1700000010/'}]},now));
console.log('17 offline assertions passed.');
